import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  page: { fontFamily: "'Inter', system-ui, sans-serif", background: "var(--bg)", color: "var(--ink)", minHeight: "100%", paddingBottom: 90 },
  header: { display: "flex", justifyContent: "space-between", alignItems: "flex-end", padding: "22px 20px 14px", borderBottom: "1px solid var(--border)", flexWrap: "wrap", gap: 10, background: "var(--card)" },
  kicker: { fontSize: 12.5, letterSpacing: 0.3, color: "var(--muted)", marginBottom: 4, fontWeight: 500 },
  title: { fontSize: 23, fontWeight: 700, margin: 0, color: "var(--header)" },
  headerRight: { display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 6 },
  urgentPill: { background: "#DC2626", color: "#FFFFFF", fontSize: 12, fontWeight: 600, padding: "4px 10px", borderRadius: 20 },
  unsetPill: { background: "transparent", border: "1px solid #D0D5DD", color: "var(--muted)", fontSize: 11.5, padding: "3px 9px", borderRadius: 20 },
  savePill: { fontSize: 11, color: "var(--muted)", fontFamily: "'IBM Plex Mono', monospace", transition: "opacity 0.4s ease" },
  helpBtn: { width: 22, height: 22, borderRadius: "50%", border: "1px solid var(--border)", background: "var(--card)", color: "var(--muted)", fontSize: 12, fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center" },
  guideBanner: { margin: "12px 16px 0", padding: "12px 14px", borderRadius: 10, border: "1px solid var(--border)", background: "var(--card)" },
  guideHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 6 },
  guideTitle: { fontSize: 13, fontWeight: 600, color: "var(--ink)" },
  guideClose: { background: "none", border: "none", color: "#98A2B3", fontSize: 17, lineHeight: 1, padding: 2 },
  guideList: { margin: 0, paddingLeft: 18, display: "flex", flexDirection: "column", gap: 4 },
  guideStep: { fontSize: 13, color: "var(--muted)", lineHeight: 1.4 },
  tabs: { display: "flex", gap: 6, padding: "12px 16px 4px", overflowX: "auto" },
  tab: { background: "var(--card)", border: "1px solid var(--border)", color: "var(--muted)", borderRadius: 20, padding: "6px 13px", fontSize: 13, whiteSpace: "nowrap" },
  tabActive: { background: "var(--header)", color: "#FFFFFF", borderColor: "var(--header)" },
  tabInput: { border: "1.5px solid var(--accent)", borderRadius: 20, padding: "6px 13px", fontSize: 13, minWidth: 90 },
  selectAllRow: { padding: "6px 16px 0", display: "flex", justifyContent: "flex-start" },
  selectAllBtn: { background: "none", border: "none", color: "var(--accent)", fontSize: 12.5, fontWeight: 600, padding: 4 },
  columnHeaders: { display: "flex", padding: "8px 20px 2px", gap: 12, fontSize: 10.5, fontWeight: 600, color: "var(--muted)", letterSpacing: 0.4, textTransform: "uppercase" },
  colHeadLeft: { flex: "1 1 0", paddingLeft: 34 },
  colHeadMiddle: { width: 64, textAlign: "center" },
  colHeadRight: { width: 52, textAlign: "center" },
  main: { padding: "4px 16px" },
  section: { marginBottom: 26 },
  sectionTitle: { fontSize: 13, fontWeight: 600, color: "var(--muted)", margin: "10px 2px 8px", letterSpacing: 0.2 },
  rowsWrap: { display: "flex", flexDirection: "column", gap: 8 },
  row: { position: "relative", border: "1px solid", borderRadius: 10, padding: "10px 14px 12px" },
  removeBtn: { position: "absolute", top: 6, right: 8, background: "none", border: "none", color: "#98A2B3", fontSize: 17, lineHeight: 1, padding: 4 },
  rowHeaderLine: { display: "flex", alignItems: "baseline", gap: 8, flexWrap: "wrap", marginBottom: 8, paddingRight: 18 },
  rowNameBtn: { fontSize: 14.5, fontWeight: 600, color: "var(--ink)", background: "none", border: "none", padding: 0, textAlign: "left", fontFamily: "inherit" },
  rowNameInput: { fontSize: 14.5, fontWeight: 600, color: "var(--ink)", border: "1.5px solid var(--accent)", borderRadius: 6, padding: "2px 6px", minWidth: 140, fontFamily: "inherit" },
  rowNote: { fontSize: 11.5, color: "var(--muted)" },
  threeCol: { display: "flex", alignItems: "center", gap: 12 },
  colLeft: { flex: "1 1 0", display: "flex", alignItems: "center", gap: 8, minWidth: 0 },
  checkboxWrap: { display: "flex" },
  checkbox: { width: 20, height: 20, accentColor: "var(--header)" },
  stepper: { display: "flex", alignItems: "center", gap: 4 },
  stepBtn: { width: 26, height: 26, borderRadius: 7, border: "1px solid var(--border)", background: "var(--card)", fontSize: 15, lineHeight: 1, color: "var(--ink)", display: "flex", alignItems: "center", justifyContent: "center" },
  stepValue: { width: 42, height: 26, textAlign: "center", background: "var(--card)", border: "1px solid var(--border)", borderRadius: 7, fontSize: 14, fontFamily: "'IBM Plex Mono', monospace", fontWeight: 600, color: "var(--ink)" },
  stepInput: { width: 42, height: 26, textAlign: "center", border: "1.5px solid var(--accent)", borderRadius: 7, fontSize: 14, fontFamily: "'IBM Plex Mono', monospace" },
  unitTag: { fontSize: 10.5, color: "var(--muted)", fontFamily: "'IBM Plex Mono', monospace" },
  colMiddle: { width: 64, display: "flex", justifyContent: "center" },
  parPill: {
    display: "inline-flex", alignItems: "center", gap: 5, height: 28, padding: "0 10px",
    borderRadius: 7, border: "1px solid var(--border)", background: "var(--card)",
    fontSize: 13, fontFamily: "'IBM Plex Mono', monospace", color: "var(--ink)", fontWeight: 600,
    transition: "box-shadow 0.3s ease, border-color 0.3s ease",
  },
  parPillFlash: { boxShadow: "0 0 0 2px #16A34A44", borderColor: "#16A34A" },
  parInputActive: { height: 28, width: 56, textAlign: "center", border: "1.5px solid var(--accent)", borderRadius: 7, fontSize: 13, fontFamily: "'IBM Plex Mono', monospace" },
  lockIcon: { fontSize: 10.5 },
  colRight: { width: 52, display: "flex", flexDirection: "column", alignItems: "center", gap: 4 },
  gaugeTrack: { width: 10, height: 34, borderRadius: 5, background: "#EDEFF2", overflow: "hidden", display: "flex", alignItems: "flex-end" },
  gaugeFill: { width: "100%", borderRadius: 5, transition: "height 0.3s ease" },
  gaugeLabel: { fontSize: 9.5, fontWeight: 700, letterSpacing: 0.2 },
  addTrigger: { marginTop: 8, background: "none", border: "1px dashed var(--border)", color: "var(--muted)", fontSize: 13, padding: "8px 10px", borderRadius: 8, width: "100%", textAlign: "left" },
  addForm: { marginTop: 8, display: "flex", flexWrap: "wrap", gap: 6, background: "var(--card)", padding: 10, borderRadius: 8, border: "1px solid var(--border)" },
  addInput: { flex: "1 1 120px", border: "1px solid var(--border)", borderRadius: 6, padding: "7px 8px", fontSize: 13 },
  addSave: { background: "var(--header)", color: "#FFFFFF", border: "none", borderRadius: 6, padding: "7px 12px", fontSize: 13, fontWeight: 600 },
  addCancel: { background: "none", border: "none", color: "var(--muted)", fontSize: 13 },
  footerBar: { position: "fixed", bottom: 0, left: 0, right: 0, background: "var(--header)", padding: "12px 18px", display: "flex", justifyContent: "space-between", alignItems: "center" },
  footerCount: { color: "#CBD2E0", fontSize: 13 },
  submitBtn: { background: "var(--accent)", color: "#FFFFFF", border: "none", fontWeight: 700, fontSize: 14, padding: "10px 18px", borderRadius: 8 },
  modalOverlay: { position: "fixed", inset: 0, background: "rgba(17,24,39,0.55)", display: "flex", alignItems: "flex-start", justifyContent: "center", padding: "40px 16px", overflowY: "auto" },
  ticket: { background: "#FFFFFF", color: "var(--ink)", fontFamily: "'IBM Plex Mono', monospace", width: 380, maxWidth: "100%", padding: 22, borderRadius: 8, boxShadow: "0 12px 30px rgba(17,24,39,0.25)" },
  ticketHeader: { display: "flex", justifyContent: "space-between", alignItems: "baseline" },
  ticketTitle: { fontWeight: 700, fontSize: 15, letterSpacing: 1 },
  ticketDate: { fontSize: 11, color: "var(--muted)" },
  ticketDivider: { borderTop: "1px dashed var(--border)", margin: "12px 0" },
  ticketCategory: { fontSize: 12, fontWeight: 700, color: "var(--muted)", marginBottom: 4 },
  ticketRow: { display: "flex", justifyContent: "space-between", fontSize: 13, padding: "2px 0" },
  ticketActions: { display: "flex", gap: 8, marginTop: 4 },
  ticketCopy: { flex: 1, background: "var(--header)", color: "#FFFFFF", border: "none", borderRadius: 6, padding: "9px 0", fontSize: 13, fontWeight: 600, fontFamily: "'Inter', sans-serif" },
  ticketExport: { flex: 1, background: "var(--accent)", color: "#FFFFFF", border: "none", borderRadius: 6, padding: "9px 0", fontSize: 13, fontWeight: 700, fontFamily: "'Inter', sans-serif" },
  ticketClose: { width: "100%", marginTop: 8, background: "none", border: "1px solid var(--border)", borderRadius: 6, padding: "9px 0", fontSize: 13, fontFamily: "'Inter', sans-serif" },
};
